baseurl: "" # the subpath of your site, e.g. /blog
<<<<<<< HEAD
url: "" # the base hostname & protocol for your site, e.g. http://example.com
=======
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
title: Ronald Berlin Architect
tagline: Princeton, NJ Architecture Firm
description: Ronald Berlin Architect - Residential Architect based in Princeton NJ
author: Sofia Berlin
logo: /assets/images/logos/PineappleLogo.jpg

# SEO
twitter:
  card: summary

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
