---
#-------------------------------
# General Site Settings

title: Ronald Berlin Architect
title-short: Ronald Berlin
logo:
author: Sofia Berlin
description: Ronald Berlin Architect - Residential Architect based in Princeton NJ
email: ronald@ronaldberlin.com
phone: +880 2544 658 256
address: 245 Jefferson Rd, Princeton, NJ, USA
copyright: Copyright &copy; 2023 Designed and Developed by [Sofia Berlin](https://github.com/sofiamay)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Ronald Berlin Architect

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Ronald Berlin Architect, P.C. translates the aspirations of its clients into beautiful and practical works of architecture. Ron’s perspective, developed over the course of two decades of professional practice, derives from his lifelong involvement in painting and sculpture, his fascination with the culture and history of architectural form, and his abiding respect for nature as the underpinning of human life.
blurb-btn-link: "/about"
blurb-btn-name: Learn more...

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#Selected Works
selected-residential:
  - content: "The Bolton Residence, Princeton, NJ"

  - content: "The Scott Apartment Remodeling, Park Avenue, New York, NY"

  - content: "The Kaczerski-Shatzkin Residence, Princeton, NJ"

  - content: "The Hodgson Residence, Ragged Mountain, Andover, New Hampshire"

  - content: "Country House and Pavilion, Kalinowka, Poland"

  - content: "Apartment combination, West 66th Street, New York, NY"

  - content: "Remodeling of residence owned by Princeton University"

  - content: "Residence of the Prince & Princess of Morocco, exterior renovations, Princeton, NJ"

  - content: "The Middlekauff-Goldin Residence, Princeton, New Jersey"

  - content: "The Browder Residence, Princeton, New Jersey"

  - content: "The DiCicco-Bloom Residence, Princeton Junction, New Jersey"

  - content: "Double Townhouse Combination, East 85th Street, New York, NY"

  - content: "The Woodrow Wilson House, Princeton, New Jersey"

  - content: "The Battle Residence, and Cottage Home Office, Princeton, New Jersey"

  - content: "The Parlapiano-Gryzbowska Residence, South Orange, New Jersey"

  - content: "The Dellenbaugh Studio and Residence, Madison, New Jersey"

  

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Web Design, color: "#fdb157", value: "90%" }
  - { name: Logo Design, color: "#9473e6", value: "60%" }
  - { name: After Effects, color: "#bdecf6", value: "80%" }
  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Junior UX Designer,
      icon: "icon-1.png",
      date: "Jan 2007 - Feb 2009",
      organization: "WEBEX",
    }
  - {
      name: UX & UI Designer,
      icon: "icon-2.png",
      date: "Mar 2009 - Aug 2014",
      organization: "AUGMEDIX",
    }
  - {
      name: Senior UI Designer,
      icon: "icon-3.png",
      date: "Sep 2014 - Present",
      organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: Education & Licensure
education:
  - {
      name: B.A.,
      date: "1976",
      organization: "Yale University",
    }
  - {
      name: Masters of Architecture,
      date: "1979",
      organization: "Princeton University",
    }
  - {
      name: State of New Jersey,
      date: "License",
      organization: "#11356",
    }
  - {
      name: Commonwealth of Pennsylvania,
      date: "License",
      organization: "#RA-013558-8",
    }
  - {
      name: State of New York,
      date: "License",
      organization: "#025588",
    }
  - {
      name: State of New Hampshire,
      date: "License",
      organization: "#3670",
    }

#-------------------------------
# Services Section

recognition-title: Recognition
recognitions:
  - {
      name: Honors,
      icon: ti-medall,
      description: "View all",
      link: honors.html,
      active: ,# Add true to select section
    }
  - {
      name: Publications,
      icon: fa-regular fa-file-lines,
      description: "View all",
      link: publications.html,
      active: true, # Add true to select section
    }
  - {
      name: Selected Work,
      icon: ti-home,
      description: "View All",
      link: selected-work.html,
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/davis_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/poland_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/wasserman_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/hodgson_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/carr_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/scott_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/veale_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/battle_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/diciccio_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/marketfair_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/west_icon.jpg"
    url: "#"

  - image: "assets/images/portfolio/writersblock_icon.jpg"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "John Garretson"
    image: "assets/images/testimonial/client-1.png"
    designation: "Garretson Custom Builders LLC"
    content: "Having worked with Ron Berlin for several years on various projects, I am thoroughly pleased as a general contractor by his collaborative spirit for problem solving, his precise and articulate style of communication and his commitment to excellence.  It's always a very satisfying experience to build work beautifully designed by Ron that is both aesthetically sensitive and practical.   He has a keen knowledge of architectural history tempered by a wonderfully creative spirit.  Ron cares about people as much as he cares about design.  He listens intently, mediates misunderstandings with diplomacy and fairness, and is unfailingly honest -- a true gentleman."

  - name: "Brad Middlekauff and Nancy Goldin"
    image: "assets/images/testimonial/client-1.png"
    designation: "Client"
    content: "We first met Ron when we were looking for an architect to help us on a small project, the conversion of a screened porch to a home office. We were so pleased with his work that subsequently we hired him for two major renovations/additions. Ron is a pleasure to work with—he is thoughtful, taking time to understand his client’s needs and preferences, creative and meticulous. He enjoys the challenges inherent in any job and has always had the ability to come up with solutions for the seemingly insurmountable problems that come with home design. Ron’s sense of humor and clear passion for what he does make working with him a delight."

  - name: "Roger Shatzkin"
    image: "assets/images/testimonial/client-1.png"
    designation: "Client"
    content: "Ron Berlin works with an architectural vision — incorporating clean and simple lines, the play of light and color, the manipulation of spatial volumes, attention to detail, and a commitment to historical authenticity. Equally important, however, is your vision as the client, and ultimately your needs come first. Ron will negotiate, coax, give in, come up with innovative alternatives, and then push himself until your plan represents the best synthesis of architect and client, and of the practical and the esthetic."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
