---
#-------------------------------
# General Site Settings

title: Ronald Berlin Architect
title-short: Ronald Berlin
logo:
author: Sofia Berlin
description: Ronald Berlin Architect - Residential Architect based in Princeton NJ
email: ronald@ronaldberlin.com
phone: +880 2544 658 256
address: 245 Jefferson Rd, Princeton, NJ, USA
copyright: Copyright &copy; 2023 Designed and Developed by [Sofia Berlin](https://github.com/sofiamay)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  # - { name: Blog, link: "/blog" }
  - { name: Recognition, link: "/recognition" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Ronald Berlin Architect

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Ronald Berlin Architect, P.C. translates the aspirations of its clients into beautiful and practical works of architecture. Ron’s perspective, developed over the course of two decades of professional practice, derives from his lifelong involvement in painting and sculpture, his fascination with the culture and history of architectural form, and his abiding respect for nature as the underpinning of human life.
blurb-btn-link: "/about"
blurb-btn-name: Learn more...

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#Selected Works
selected-residential:
  - content: "The Bolton Residence, Princeton, NJ"

  - content: "The Scott Apartment Remodeling, Park Avenue, New York, NY"

  - content: "The Kaczerski-Shatzkin Residence, Princeton, NJ"

  - content: "The Hodgson Residence, Ragged Mountain, Andover, New Hampshire"

  - content: "Country House and Pavilion, Kalinowka, Poland"

  - content: "Apartment combination, West 66th Street, New York, NY"

  - content: "Remodeling of residence owned by Princeton University"

  - content: "Residence of the Prince & Princess of Morocco, exterior renovations, Princeton, NJ"

  - content: "The Middlekauff-Goldin Residence, Princeton, New Jersey"

  - content: "The Browder Residence, Princeton, New Jersey"

  - content: "The DiCicco-Bloom Residence, Princeton Junction, New Jersey"

  - content: "Double Townhouse Combination, East 85th Street, New York, NY"

  - content: "The Woodrow Wilson House, Princeton, New Jersey"

  - content: "The Battle Residence, and Cottage Home Office, Princeton, New Jersey"

  - content: "The Parlapiano-Gryzbowska Residence, South Orange, New Jersey"

  - content: "The Dellenbaugh Studio and Residence, Madison, New Jersey"

selected-commercial:
  - content: "The Baxter Commercial Property, Hopewell, NJ"

  - content: "Master Plan for St. Joseph’s Roman Catholic Church, Trenton, New Jersey"

  - content: "Offices for Tucker Capital, Princeton, New Jersey"

  - content: "The Sciarra Painting Studio, Lawrenceville, New Jersey"

  - content: "Ichiban Japanese Restaurant, Princeton, New Jersey"

  - content: "The Food Court at Market Fair, West Windsor, New Jersey (w/Max Hayden)"

  - content: "Offices for Gordon Tracy, Bucks County, Pennsylvania"

  - content: "Delaware-Raritan Girl Scouts Council Building Rehabilitation, New Jersey"

  - content: "The Weiss Sculpture Studio, Princeton, New Jersey"

  - content: "Factory Rehabilitation for L.T.S. Incorporated, Trenton, New Jersey"

  - content: "Feasibility Studies for the City of Brisbane, California"






  

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Web Design, color: "#fdb157", value: "90%" }
  - { name: Logo Design, color: "#9473e6", value: "60%" }
  - { name: After Effects, color: "#bdecf6", value: "80%" }
  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Junior UX Designer,
      icon: "icon-1.png",
      date: "Jan 2007 - Feb 2009",
      organization: "WEBEX",
    }
  - {
      name: UX & UI Designer,
      icon: "icon-2.png",
      date: "Mar 2009 - Aug 2014",
      organization: "AUGMEDIX",
    }
  - {
      name: Senior UI Designer,
      icon: "icon-3.png",
      date: "Sep 2014 - Present",
      organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: Education & Licensure
education:
  - {
      name: B.A.,
      date: "1976",
      organization: "Yale University",
    }
  - {
      name: Masters of Architecture,
      date: "1979",
      organization: "Princeton University",
    }
  - {
      name: State of New Jersey,
      date: "License",
      organization: "#11356",
    }
  - {
      name: Commonwealth of Pennsylvania,
      date: "License",
      organization: "#RA-013558-8",
    }
  - {
      name: State of New York,
      date: "License",
      organization: "#025588",
    }
  - {
      name: State of New Hampshire,
      date: "License",
      organization: "#3670",
    }

#-------------------------------
# Services Section

recognition-title: Recognition
recognitions:
  - {
      name: Honors,
      icon: ti-medall,
      description: "View all",
      link: honors.html,
      active: ,# Add true to select section
    }
  - {
      name: Publications,
      icon: fa-regular fa-file-lines,
      description: "View all",
      link: publications.html,
      active: true, # Add true to select section
    }
  - {
      name: Selected Work,
      icon: ti-home,
      description: "View All",
      link: selected-work.html,
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/davis_icon.jpg"
    url: "#"
    modal-id: "davis"

  - image: "assets/images/portfolio/poland_icon.jpg"
    url: "#"
    modal-id: "poland"

  - image: "assets/images/portfolio/wasserman_icon.jpg"
    url: "#"
    modal-id: "wasserman"

  - image: "assets/images/portfolio/hodgson_icon.jpg"
    url: "#"
    modal-id: "hodgson"

  - image: "assets/images/portfolio/carr_icon.jpg"
    url: "#"
    modal-id: "carr"

  - image: "assets/images/portfolio/scott_icon.jpg"
    url: "#"
    modal-id: "scott"

  - image: "assets/images/portfolio/veale_icon.jpg"
    url: "#"
    modal-id: "veale"

  - image: "assets/images/portfolio/battle_icon.jpg"
    url: "#"
    modal-id: "battle"

  - image: "assets/images/portfolio/bloom_icon.jpg"
    url: "#"
    modal-id: "bloom"

  - image: "assets/images/portfolio/marketfair_icon.jpg"
    url: "#"
    modal-id: "marketfair"

  - image: "assets/images/portfolio/west_icon.jpg"
    url: "#"
    modal-id: west"

  - image: "assets/images/portfolio/writersblock_icon.jpg"
    url: "#"
    modal-id: "writersblock"

# Portfolio Page

portfolio-label:
  - { title: "RESIDENTIAL", type: "residential" }
  - { title: "COMMERCIAL", type: "commercial" }
  - { title: "PRAISED", type: "honored" }

portfolio-items:
  - image: "assets/images/portfolio/davis_icon.jpg"
    url: "#"
    modal-id: "davis"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/poland_icon.jpg"
    url: "#"
    modal-id: "poland"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/wasserman_icon.jpg"
    url: "#"
    modal-id: "wasserman"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/hodgson_icon.jpg"
    url: "#"
    modal-id: "hodgson"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/carr_icon.jpg"
    url: "#"
    modal-id: "carr"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/scott_icon.jpg"
    url: "#"
    modal-id: "scott"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/veale_icon.jpg"
    url: "#"
    modal-id: "veale"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/battle_icon.jpg"
    url: "#"
    modal-id: "battle"
    portfolio-type:
      - type: "residential"
      - type: "honored"

  - image: "assets/images/portfolio/bloom_icon.jpg"
    url: "#"
    modal-id: "bloom"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/marketfair_icon.jpg"
    url: "#"
    modal-id: "marketfair"
    portfolio-type:
      - type: "commercial"
      - type: "honored"

  - image: "assets/images/portfolio/west_icon.jpg"
    url: "#"
    modal-id: "west"
    portfolio-type:
      - type: "residential"

  - image: "assets/images/portfolio/writersblock_icon.jpg"
    url: "#"
    modal-id: "writersblock"
    portfolio-type:
      - type: "commercial"
      - type: "honored"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "John Garretson"
    image: "assets/images/testimonial/client-1.png"
    designation: "Garretson Custom Builders LLC"
    content: "Having worked with Ron Berlin for several years on various projects, I am thoroughly pleased as a general contractor by his collaborative spirit for problem solving, his precise and articulate style of communication and his commitment to excellence.  It's always a very satisfying experience to build work beautifully designed by Ron that is both aesthetically sensitive and practical.   He has a keen knowledge of architectural history tempered by a wonderfully creative spirit.  Ron cares about people as much as he cares about design.  He listens intently, mediates misunderstandings with diplomacy and fairness, and is unfailingly honest -- a true gentleman."

  - name: "Brad Middlekauff and Nancy Goldin"
    image: "assets/images/testimonial/client-1.png"
    designation: "Client"
    content: "We first met Ron when we were looking for an architect to help us on a small project, the conversion of a screened porch to a home office. We were so pleased with his work that subsequently we hired him for two major renovations/additions. Ron is a pleasure to work with—he is thoughtful, taking time to understand his client’s needs and preferences, creative and meticulous. He enjoys the challenges inherent in any job and has always had the ability to come up with solutions for the seemingly insurmountable problems that come with home design. Ron’s sense of humor and clear passion for what he does make working with him a delight."

  - name: "Roger Shatzkin"
    image: "assets/images/testimonial/client-1.png"
    designation: "Client"
    content: "Ron Berlin works with an architectural vision — incorporating clean and simple lines, the play of light and color, the manipulation of spatial volumes, attention to detail, and a commitment to historical authenticity. Equally important, however, is your vision as the client, and ultimately your needs come first. Ron will negotiate, coax, give in, come up with innovative alternatives, and then push himself until your plan represents the best synthesis of architect and client, and of the practical and the esthetic."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Recoognition Section

honors:
  - award: "LEED Silver certification, The Whole Earth Center"
    org: "Awarded by the US Green Building Council"
    year: "2010"

  - award: "Award for Historic Preservation, The Residence of the Prince of Morocco"
    org: "The Historical Society of Princeton"
    year: "2009"

  - award: "2006 New Jersey Historic Preservation Award"
    org: "State of New Jersey Department of Environmental Protection"
    year: "2007"

  - award: "New Jersey A.I.A. Honor Award for Excellence in Architecture"
    org: "Princeton Writers' Block"
    year: "2005"

  - award: "New Jersey A.I.A. Smart Growth Architecture Award"
    org: "Princeton Writers' Block"
    year: "2004"

  - award: "Finalist, Municipal Building Design Competition"
    org: "Princeton Township"
    year: "1997"

  - award: "Award for Historic Preservation, The Captain’s House"
    org: "The Historical Society of Princeton"
    year: "1995"

  - award: "The Liskin Foundation Award"
    org: "The National Sculpture Society"
    year: "1989"

  - award: "Special Patrons' Award for Sculpture"
    org: "The Phillips Mill Associationn"
    year: "1982"

  - award: "The Reed Prize for Drawing"
    org: "The Newport Art Associatio"
    year: "1981"

  - award: "The Gordon McCormack Fellowship"
    org: "Princeton University"
    year: "1978-1979"

  - award: "Honors in Art and Architecture"
    org: "Yale University"
    year: "1976"

pro-bono:
  - title: "Founding member"
    description: "The Princeton Community Pool Ad Hoc Committee"

  - title: "Talk, 'Old Housekeeping', Joint Historic & Sustainability Workshop"
    description: "Princeton Public Library"
    year: "2010"

  - title: "Talk, 'The Woodrow Wilson House', Joint Historic & Sustainability Workshop"
    description: "The Nassau Club, Princeton, NJ"
    year: "2009"

  - title: "Princeton Environmental Commission"
    description: "Green Home and Garden Tour"

  - title: "'Princeton Writers Block' Folly [a writer/architect collaboration]"
    description: "Awarded by the US Green Building Council"
    year: "2010"

  - title: "LEED Silver certification, The Whole Earth Center"
    description: "w/ Paul Krugman"
    year: "2004"

  - title: "Former Chairman, Site Plan Review Advisory Board"
    description: "Princeton Borough & Township"

  - title: "Member and former Trustee"
    description: "The Friends of Princeton Open Space"

  - title: "Trustee and Founder"
    description: "The Friends of the Institute Land"

publications-1:
  - title: "Presidential Style"
    publisher: "Princeton Magazine"
    date: "August, 2009"

  - title: "Whole Earth Gets a 21st Century Facelift"
    publisher: "Cover Story, U.S. 1 Newspaper"
    date: "April 2, 2008"

  - title: "Want to Live Sustainably?"
    publisher: "Town Topics"
    date: "September 26, 2007"

  - title: "Whole (New) Earth Center"
    publisher: "The Princeton Packet"
    date: "September 18, 2007"

  - title: "Princeton Architect Gives Castle the Royal Treatment"
    publisher: "The Trenton Times"
    date: "Aug. 2, 2005"

  - title: "Sacred Spaces"
    publisher: "Tunnell, Engelbert, and Szymanski,"
    date: "2004"

  - title: “Writers Serve as Muses for Architects’ Projects in Princeton”
    publisher: "Architectural Record"
    date: " October, 2004"

  - title: “Rooms with a High Interest Rate”
    publisher: "Design New Jersey"
    date: "October 2004"

  - title: “Sacred Space”
    publisher: "The Princeton Packet"
    date: "August 11, 2000"

publications-2:
  - title: 'Adaptive Reuse: Uncommonly Unusual'
    publisher: "Renovation Style"
    date: "Winter, 1998"

  - title: "[Unknown Title]"
    publisher: "Architectural Digest, German Edition"
    date: "October/November 1998"

  - title: “Food For Thought”
    publisher: "Architectural Record"
    date: "May, 1998"

  - title: “A Great Second Act”
    publisher: "House and Garden"
    date: "February, 1998"

  - title: "[Unknown Title]"
    publisher: "The New York Times"
    date: "August 16, 1997"

  - title: “Berlin’s Blue”
    publisher: "U.S. 1 Newspaper"
    date: "November 20, 1996"

  - title: “Mixing Business with Pleasure”
    publisher: "Princeton Living"
    date: "December, 1995"

  - title: "Architectural Detailing in Contract Interiors"
    publisher: "W.W. Staebler, Whitney Library of Design"
    date: "1988"

  - title: "A House That Bloomed"
    publisher: "Connecticut Magazine"
    date: "May, 1988"

  - title: "[Unknown Title]"
    publisher: "The New York Times"
    date: "June 12, 1983"


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
